// Generated by CoffeeScript 1.9.3
(function() {
  var CategorySchema, ObjectId, Schema, mongoose;

  mongoose = require("mongoose");

  Schema = mongoose.Schema;

  ObjectId = Schema.Types.ObjectId;

  CategorySchema = new Schema({
    name: String,
    movies: [
      {
        type: ObjectId,
        ref: 'Movie'
      }
    ],
    meta: {
      createAt: {
        type: Date,
        "default": Date.now()
      },
      updateAt: {
        type: Date,
        "default": Date.now()
      }
    }
  });

  CategorySchema.pre('save', function(next) {
    if (this.isNew) {
      this.meta.createAt = this.meta.updateAt = Date.now();
    } else {
      this.meta.createAt = Date.now();
    }
    return next();
  });

  CategorySchema.statics = {
    fetch: function(cb) {
      return this.find({}).sort('meta.updateAt').exec(cb);
    },
    findById: function(id, cb) {
      return this.findOne({
        _id: id
      }).exec(cb);
    }
  };

  module.exports = CategorySchema;

}).call(this);

//# sourceMappingURL=category.js.map
