// Generated by CoffeeScript 1.9.3
(function() {
  var Comment;

  Comment = require('../models/comment');

  exports.save = function(req, res) {
    var _comment, comment, movieId;
    _comment = req.body;
    console.log(_comment);
    movieId = _comment.movie;
    if (_comment.cid) {
      return Comment.findById(_comment.cid, function(err, comment) {
        var reply;
        reply = {
          from: _comment.from,
          to: _comment.tid,
          content: _comment.content
        };
        comment.reply.push(reply);
        return comment.save(function(err, comment) {
          if (err) {
            console.log(err);
          }
          return res.redirect('/movie/' + movieId);
        });
      });
    } else {
      comment = new Comment(_comment);
      return comment.save(function(err, comment) {
        if (err) {
          console.log(err);
        }
        return res.redirect('/movie/' + movieId);
      });
    }
  };

}).call(this);

//# sourceMappingURL=comment.js.map
