// Generated by CoffeeScript 1.9.3
(function() {
  var Category, CategorySchema, mongoose;

  mongoose = require('mongoose');

  CategorySchema = require('../schemas/category');

  Category = mongoose.model('Category', CategorySchema);

  module.exports = Category;

}).call(this);

//# sourceMappingURL=category.js.map
