// Generated by CoffeeScript 1.9.3
(function() {
  var Comment, CommentSchema, mongoose;

  mongoose = require('mongoose');

  CommentSchema = require('../schemas/comment');

  Comment = mongoose.model('Comment', CommentSchema);

  module.exports = Comment;

}).call(this);

//# sourceMappingURL=comment.js.map
