// Generated by CoffeeScript 1.9.3
(function() {
  var User, UserSchema, mongoose;

  mongoose = require('mongoose');

  UserSchema = require('../schemas/user');

  User = mongoose.model('User', UserSchema);

  module.exports = User;

}).call(this);

//# sourceMappingURL=user.js.map
